cache:
    paths:
    - target/
    - cargo/

test:1.13:
    image: "scorpil/rust:1.13"
    script:
    - cargo build --verbose

test:stable:
    image: "scorpil/rust:stable"
    script:
    - cargo build --verbose

test:beta:
    image: "scorpil/rust:beta"
    script:
    - cargo build --verbose

test:nightly:
    image: "scorpil/rust:nightly"
    script:
    - cargo build --verbose
