[package]
name = "serialport"
version = "0.9.0"
authors = ["Bryant Mairs <bryant@mai.rs>"]
categories = ["hardware-support"]
keywords = ["serial", "hardware", "system", "RS232"]
license = "LGPL-3.0"
readme = "README.asciidoc"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"

[badges]
gitlab = { repository = "susurrus/serialport-rs" }
appveyor = { repository = "Susurrus/serialport-rs", service = "gitlab" }

[dev-dependencies]
argparse = "0.2"

[dependencies]
libc = "0.2.1"

[target."cfg(unix)".dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "0.2.0"

[target."cfg(windows)".dependencies]
winreg = "0.3"
