[package]
name = "serialport"
version = "1.0.2-pre"
authors = ["Bryant Mairs <bryant@mai.rs>"]
categories = ["hardware-support"]
keywords = ["serial", "hardware", "system", "RS232"]
license = "MPL-2.0"
readme = "README.asciidoc"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"

[badges]
appveyor = { repository = "Susurrus/serialport-rs", service = "gitlab" }
gitlab = { repository = "susurrus/serialport-rs" }
travis = { repository = "Susurrus/serialport-rs" }

[dev-dependencies]
argparse = "0.2"

[dependencies]
libc = "0.2.1"

[target."cfg(unix)".dependencies]
ioctl-rs = "0.1.5"
nix = { path = "nix" }
termios = "0.2.2"

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "0.2.0"

[target."cfg(windows)".dependencies]
advapi32-sys = { path = "winapi-rs/lib/advapi32" }
kernel32-sys = { path = "winapi-rs/lib/kernel32" }
regex = "0.2"
setupapi-sys = { path = "winapi-rs/lib/setupapi" }
winapi = { path = "winapi-rs" }

[target.'cfg(target_os = "macos")'.dependencies]
IOKit-sys = "0.1"
mach = "0.0.5"
CoreFoundation-sys = "0.1.3"
