[package]
name = "serialport"
version = "0.2.0"
authors = ["Bryant Mairs <bryant@mai.rs>"]
keywords = ["serial", "hardware", "system", "RS232"]
license = "LGPL-3.0"
readme = "README.asciidoc"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"

[dev-dependencies]
argparse = "0.2"

[dependencies]
libc = "0.2.1"

[target.aarch64-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.arm-unknown-linux-gnueabi.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.arm-unknown-linux-gnueabihf.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.armv7-unknown-linux-gnueabihf.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.i686-apple-darwin.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.i686-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
libudev = "0.2.0"
termios = "0.2.2"

[target.mips-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
libudev = "0.2.0"
termios = "0.2.2"

[target.mipsel-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
libudev = "0.2.0"
termios = "0.2.2"

[target.powerpc-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
libudev = "0.2.0"
termios = "0.2.2"

[target.x86_64-apple-darwin.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.x86_64-unknown-dragonfly.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.x86_64-unknown-freebsd.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.x86_64-unknown-linux-gnu.dependencies]
ioctl-rs = "0.1.5"
libudev = "0.2.0"
termios = "0.2.2"

[target.x86_64-unknown-openbsd.dependencies]
ioctl-rs = "0.1.5"
termios = "0.2.2"

[target.i686-pc-windows-msvc.dependencies]
winreg = "0.3"

[target.x86_64-pc-windows-msvc.dependencies]
winreg = "0.3"

[target.i686-pc-windows-gnu.dependencies]
winreg = "0.3"

[target.x86_64-pc-windows-gnu.dependencies]
winreg = "0.3"
