name: Lint

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      args:
        type: string

env:
  # Pretty cargo output!
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint | install dependencies
        run: |
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/' /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt install -qq -y libudev-dev

      - name: Lint | checkout
        uses: actions/checkout@v2

      - name: Lint | install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Lint | rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Lint | lint library
        uses: actions-rs/cargo@v1
        with:
          command: ${{ inputs.command }}
          args: ${{ inputs.args }}
